net_name: YoloV4
num_cls: 80
anchor_ch: 255
img_size: [3, 608, 608]
layers_fn: create_yolo_blocks

batch: 64
subdivisions: 8
# Training
#width: 512
#height: 512
width: 608
height: 608
channels: 3
momentum: 0.949
decay: 0.0005
angle: 0
saturation :  1.5
exposure :  1.5
hue: .1

learning_rate: 0.0013
burn_in: 1000
max_batches :  500500
policy: steps
steps: 400000,450000
scales: .1,.1

#cutmix: 1
mosaic: 1

#:104x104 54:52x52 85:26x26 104:13x13 for 416
# Shortcut: args[residual_path='equal', activation='relu'], kwargs[out_ch, pool_size]
# ConvSameBnRelu2D: args[out_ch, kernel_size=1, stride=1, padding='valid', activation='valid', bn=False, groups=1]
backbone:
  [
    [-1, 1, ConvSameBnRelu2D, [32, 3], {activation: mish}],       # 1

    # Down sample 1
    [-1, 1, ConvSameBnRelu2D, [64, 3, 2], {activation: mish}],
    [-1, 1, ConvSameBnRelu2D, [64], {activation: mish}],
    [-1, 1, ConvSameBnRelu2D, [32], {activation: mish}],
    [-1, 1, ConvSameBnRelu2D, [64, 3], {activation: mish}],
    [[-3, -1], 1, Shortcut, [equal]],
    [-1, 1, ConvSameBnRelu2D, [64], {activation: mish}],
    [-6, 1, ConvSameBnRelu2D, [64], {activation: mish}],
    [[-2, -1], 1, Concat, {dim: 1}],
    [-1, 1, ConvSameBnRelu2D, [64], {activation: mish}],          # 10

    # Down sample 2
    [-1, 1, ConvSameBnRelu2D, [128, 3, 2], {activation: mish}],
    [-1, 1, ConvSameBnRelu2D, [64], {activation: mish}],
    [-1, 1, ConvSameBnRelu2D, [64], {activation: mish}],
    [-1, 1, ConvSameBnRelu2D, [64, 3], {activation: mish}],
    [[-3, -1], 1, Shortcut, [equal]],
    [-1, 1, ConvSameBnRelu2D, [64], {activation: mish}],
    [-1, 1, ConvSameBnRelu2D, [64, 3], {activation: mish}],
    [[-3, -1], 1, Shortcut, [equal]],
    [-1, 1, ConvSameBnRelu2D, [64], {activation: mish}],
    [-9, 1, ConvSameBnRelu2D, [64], {activation: mish}],        # 20
    [[-2, -1], 1, Concat, {dim: 1}],
    [-1, 1, ConvSameBnRelu2D, [128], {activation: mish}],

    # Down sample 3
    [-1, 1, ConvSameBnRelu2D, [256, 3, 2], {activation: mish}],
    [-1, 1, ConvSameBnRelu2D, [128], {activation: mish}],
    [-1, 1, ConvSameBnRelu2D, [128], {activation: mish}],
    [-1, 1, ConvSameBnRelu2D, [128, 3], {activation: mish}],
    [[-3, -1], 1, Shortcut, [equal]],
    [-1, 1, ConvSameBnRelu2D, [128], {activation: mish}],
    [-1, 1, ConvSameBnRelu2D, [128, 3], {activation: mish}],
    [[-3, -1], 1, Shortcut, [equal]],                              # 30
    [-1, 1, ConvSameBnRelu2D, [128], {activation: mish}],
    [-1, 1, ConvSameBnRelu2D, [128, 3], {activation: mish}],
    [[-3, -1], 1, Shortcut, [equal]],
    [-1, 1, ConvSameBnRelu2D, [128], {activation: mish}],
    [-1, 1, ConvSameBnRelu2D, [128, 3], {activation: mish}],
    [[-3, -1], 1, Shortcut, [equal]],
    [-1, 1, ConvSameBnRelu2D, [128], {activation: mish}],
    [-1, 1, ConvSameBnRelu2D, [128, 3], {activation: mish}],
    [[-3, -1], 1, Shortcut, [equal]],
    [-1, 1, ConvSameBnRelu2D, [128], {activation: mish}],       # 40
    [-1, 1, ConvSameBnRelu2D, [128, 3], {activation: mish}],
    [[-3, -1], 1, Shortcut, [equal]],
    [-1, 1, ConvSameBnRelu2D, [128], {activation: mish}],
    [-1, 1, ConvSameBnRelu2D, [128, 3], {activation: mish}],
    [[-3, -1], 1, Shortcut, [equal]],
    [-1, 1, ConvSameBnRelu2D, [128], {activation: mish}],
    [-1, 1, ConvSameBnRelu2D, [128, 3], {activation: mish}],
    [[-3, -1], 1, Shortcut, [equal]],
    [-1, 1, ConvSameBnRelu2D, [128], {activation: mish}],
    [-27, 1, ConvSameBnRelu2D, [128], {activation: mish}],      # 50
    [[-2, -1], 1, Concat, {dim: 1}],
    [-1, 1, ConvSameBnRelu2D, [256], {activation: mish}],

    # Down sample 4
    [-1, 1, ConvSameBnRelu2D, [512, 3, 2], {activation: mish}],
    [-1, 1, ConvSameBnRelu2D, [256], {activation: mish}],
    [-1, 1, ConvSameBnRelu2D, [256], {activation: mish}],
    [-1, 1, ConvSameBnRelu2D, [256, 3], {activation: mish}],
    [[-3, -1], 1, Shortcut, [equal]],
    [-1, 1, ConvSameBnRelu2D, [256], {activation: mish}],
    [-1, 1, ConvSameBnRelu2D, [256, 3], {activation: mish}],
    [[-3, -1], 1, Shortcut, [equal]],                           # 60
    [-1, 1, ConvSameBnRelu2D, [256], {activation: mish}],
    [-1, 1, ConvSameBnRelu2D, [256, 3], {activation: mish}],
    [[-3, -1], 1, Shortcut, [equal]],
    [-1, 1, ConvSameBnRelu2D, [256], {activation: mish}],
    [-1, 1, ConvSameBnRelu2D, [256, 3], {activation: mish}],
    [[-3, -1], 1, Shortcut, [equal]],
    [-1, 1, ConvSameBnRelu2D, [256], {activation: mish}],
    [-1, 1, ConvSameBnRelu2D, [256, 3], {activation: mish}],
    [[-3, -1], 1, Shortcut, [equal]],
    [-1, 1, ConvSameBnRelu2D, [256], {activation: mish}],       # 70
    [-1, 1, ConvSameBnRelu2D, [256, 3], {activation: mish}],
    [[-3, -1], 1, Shortcut, [equal]],
    [-1, 1, ConvSameBnRelu2D, [256], {activation: mish}],
    [-1, 1, ConvSameBnRelu2D, [256, 3], {activation: mish}],
    [[-3, -1], 1, Shortcut, [equal]],
    [-1, 1, ConvSameBnRelu2D, [256], {activation: mish}],
    [-1, 1, ConvSameBnRelu2D, [256, 3], {activation: mish}],
    [[-3, -1], 1, Shortcut, [equal]],
    [-1, 1, ConvSameBnRelu2D, [256], {activation: mish}],
    [-27, 1, ConvSameBnRelu2D, [256], {activation: mish}],      # 80
    [[-2, -1], 1, Concat, {dim: 1}],
    [-1, 1, ConvSameBnRelu2D, [512], {activation: mish}],

    # Down sample 5
    [-1, 1, ConvSameBnRelu2D, [1024, 3, 2], {activation: mish}],
    [-1, 1, ConvSameBnRelu2D, [512], {activation: mish}],
    [-1, 1, ConvSameBnRelu2D, [512], {activation: mish}],
    [-1, 1, ConvSameBnRelu2D, [512, 3], {activation: mish}],
    [[-3, -1], 1, Shortcut, [equal]],
    [-1, 1, ConvSameBnRelu2D, [512], {activation: mish}],
    [-1, 1, ConvSameBnRelu2D, [512, 3], {activation: mish}],
    [[-3, -1], 1, Shortcut, [equal]],                           # 90
    [-1, 1, ConvSameBnRelu2D, [512], {activation: mish}],
    [-1, 1, ConvSameBnRelu2D, [512, 3], {activation: mish}],
    [[-3, -1], 1, Shortcut, [equal]],
    [-1, 1, ConvSameBnRelu2D, [512], {activation: mish}],
    [-1, 1, ConvSameBnRelu2D, [512, 3], {activation: mish}],
    [[-3, -1], 1, Shortcut, [equal]],
    [-1, 1, ConvSameBnRelu2D, [512], {activation: mish}],
    [-15, 1, ConvSameBnRelu2D, [512], {activation: mish}],
    [[-2, -1], 1, Concat, {dim: 1}],
    [-1, 1, ConvSameBnRelu2D, [1024], {activation: mish}],    # 100

    ##########################
    [-1, 1, ConvSameBnRelu2D, [512], {activation: leaky}],
    [-1, 1, ConvSameBnRelu2D, [1024, 3], {activation: leaky}],
    [-1, 1, ConvSameBnRelu2D, [512], {activation: leaky}],

    # SPP
    [-1, 1, MaxPool2D, [5, 1], {padding: same}],
    [-2, 1, MaxPool2D, [9, 1], {padding: same}],
    [-3, 1, MaxPool2D, [13, 1], {padding: same}],
    [[-1, -2, -3, -4], 1, Concat, {dim: 1}],
    # End SPP

    [-1, 1, ConvSameBnRelu2D, [512], {activation: leaky}],
    [-1, 1, ConvSameBnRelu2D, [1024, 3], {activation: leaky}],
    [-1, 1, ConvSameBnRelu2D, [512], {activation: leaky}],      # 110
    [-1, 1, ConvSameBnRelu2D, [256], {activation: leaky}],
    [-1, 1, UpSample, {stride: 2}],
    [81, 1, ConvSameBnRelu2D, [256], {activation: leaky}],
    [[-1, -2], 1, Concat, {dim: 1}],

    [-1, 1, ConvSameBnRelu2D, [256], {activation: leaky}],
    [-1, 1, ConvSameBnRelu2D, [512, 3], {activation: leaky}],
    [-1, 1, ConvSameBnRelu2D, [256], {activation: leaky}],
    [-1, 1, ConvSameBnRelu2D, [512, 3], {activation: leaky}],
    [-1, 1, ConvSameBnRelu2D, [256], {activation: leaky}],
    [-1, 1, ConvSameBnRelu2D, [128], {activation: leaky}],      # 120
    [-1, 1, UpSample, {stride: 2}],
  ]


# Yolo: args[num_cls, num, jitter, ignore_thresh, scale_x_y, iou_thresh, cls_normalizer, iou_normalizer, beta_nms]
# kwargs[random, mask, iou_loss, nms_kind]
anchors: [[12, 16], [19, 36], [40, 28], [36, 75], [76, 55], [72, 146], [142, 110], [192, 243], [459, 401]]
head:
  [
    # YoloNeck 1
    [[48, -1], 1, YoloNeck, [128], {activation: leaky, dim: 1}],    # Concat: out_ch 256

    # YoloBlock
    [-1, 1, YoloBlock, [128], {kernels_size: [1, 3], activation: leaky}],

    # Classifier
    # [-1, 1, ConvSameBnRelu2D, [anchor_ch], {activation: valid}],
    [-1, 1, YoloClassifier, [anchor_ch, 256],
      {yolo_args: [num_cls, 9, .3, .7, 1, 1.2, 0.213, 1.0, 0.07, 0.6],
       activation: valid, mask: [0, 1, 2], iou_loss: ciou, nms_kind: greedynms}],

    # YoloNeck 2
    [[-3, -7], 1, YoloNeck, [256, 3, 2], {activation: leaky, dim: 1}],  # Concat: out_ch 512

    # YoloBlock
    [-1, 1, YoloBlock, [256], {kernels_size: [1, 3], activation: leaky}],

    # Classifier
    [-1, 1, YoloClassifier, [anchor_ch, 512],
      {yolo_args: [num_cls, 9, .3, .7, 1, 1.1, 0.213, 1.0, 0.07, 0.6],
       activation: valid, mask: [0, 1, 2], iou_loss: ciou, nms_kind: greedynms}],

    # YoloNeck 3
    [[-3, -20], 1, YoloNeck, [512, 3, 2], {activation: leaky, dim: 1}], # Concat: out_ch 1024

    # YoloBlock
    [-1, 1, YoloBlock, [512], {kernels_size: [1, 3], activation: leaky}],

    # Classifier
    [-1, 1, YoloClassifier, [anchor_ch, 1024],
      {yolo_args: [num_cls, 9, .3, .7, 1, 1, 1.05, 0.213, 1.0, 0.07, 0.6],
       activation: valid, random: 1, mask: [0, 1, 2], iou_loss: ciou, nms_kind: greedynms}],

    [[-1, -5, -9], 1, Concat, {dim: 0}]
  ]
